---
name: AntiTrampleFarmland
version: 0.0.2
main: NhanAZ\AntiTrampleFarmland\Main
api: 5.0.0
website: https://github.com/NhanAZ
author: NhanAZ
description: Farmland will not decay when trampled by any entity
...
